#!/usr/bin/env node

const { execSync } = require('child_process')
const run = cmd => execSync(cmd, { stdio: 'inherit' })

if (process.env.CI) {
  run('npm run test:ci')
} else {
  run('npm run test:dev')
}
